repos:
-   repo: https://github.com/matthewhughes934/pre-commit-format-markdown
    rev: v0.5.0
    hooks:
    -   id: format-markdown-docker
-   repo: https://gitlab.com/matthewhughes/common-changelog
    rev: v0.1.1
    hooks:
    -   id: validate-changelog
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3
    hooks:
    -   id: golangci-lint
-   repo: https://github.com/segmentio/golines
    rev: v0.11.0
    hooks:
    -   id: golines
