// Code generated by ../../scripts/copy-lib ../../cmark-gfm-src at 587a12bb54d95ac37241377e6ddc93ea0e45439b DO NOT EDIT.
// See ../../cmark-gfm-src/COPYING for license
#ifndef CMARK_GFM_VERSION_H
#define CMARK_GFM_VERSION_H

#define CMARK_GFM_VERSION ((0 << 24) | (29 << 16) | (0 << 8) | 13)
#define CMARK_GFM_VERSION_STRING "0.29.0.gfm.13"

#endif
