// Code generated by ../../scripts/copy-lib ../../cmark-gfm-src at 1e230827a584ebc9938c3eadc5059c55ef3c9abf DO NOT EDIT.
// See ../../cmark-gfm-src/COPYING for license
#ifndef CMARK_GFM_VERSION_H
#define CMARK_GFM_VERSION_H

#define CMARK_GFM_VERSION ((0 << 24) | (29 << 16) | (0 << 8) | 11)
#define CMARK_GFM_VERSION_STRING "0.29.0.gfm.11"

#endif
