// Code generated by ../../scripts/copy-lib ../../cmark-gfm-src at 587a12bb54d95ac37241377e6ddc93ea0e45439b DO NOT EDIT.
// See ../../cmark-gfm-src/COPYING for license
#ifndef CMARK_GFM_TABLE_H
#define CMARK_GFM_TABLE_H

#include "cmark-gfm-core-extensions.h"


extern cmark_node_type CMARK_NODE_TABLE, CMARK_NODE_TABLE_ROW,
    CMARK_NODE_TABLE_CELL;

cmark_syntax_extension *create_table_extension(void);

#endif
