// Code generated by ../../scripts/copy-lib ../../cmark-gfm-src at 587a12bb54d95ac37241377e6ddc93ea0e45439b DO NOT EDIT.
// See ../../cmark-gfm-src/COPYING for license
#ifndef TASKLIST_H
#define TASKLIST_H

#include "cmark-gfm-core-extensions.h"

cmark_syntax_extension *create_tasklist_extension(void);

#endif
