// Code generated by ../../scripts/copy-lib ../../cmark-gfm-src at 1e230827a584ebc9938c3eadc5059c55ef3c9abf DO NOT EDIT.
// See ../../cmark-gfm-src/COPYING for license
#ifndef TASKLIST_H
#define TASKLIST_H

#include "cmark-gfm-core-extensions.h"

cmark_syntax_extension *create_tasklist_extension(void);

#endif
