// Code generated by ../../scripts/copy-lib ../../cmark-src/ at +8fbf029685482827828b5858444157052f1b0a5f DO NOT EDIT.
// See ../../cmark-src//COPYING for license
#ifndef CMARK_VERSION_H
#define CMARK_VERSION_H

#define CMARK_VERSION ((0 << 16) | (30 << 8)  | 3)
#define CMARK_VERSION_STRING "0.30.3"

#endif
