// Code generated by ../../scripts/copy-lib ../../cmark-src at bb3678d7a73cb02d35c8876ecd097072636200a8 DO NOT EDIT.
// See ../../cmark-src/COPYING for license
#ifndef CMARK_VERSION_H
#define CMARK_VERSION_H

#define CMARK_VERSION ((0 << 16) | (31 << 8)  | 1)
#define CMARK_VERSION_STRING "0.31.1"

#endif
