// Code generated by ../../scripts/copy-lib ../../cmark-src at 5ba25ff40eba44c811f79ab6a792baf945b8307c DO NOT EDIT.
// See ../../cmark-src/src/COPYING for license
#ifndef CMARK_VERSION_H
#define CMARK_VERSION_H

#define CMARK_VERSION ((0 << 16) | (30 << 8)  | 3)
#define CMARK_VERSION_STRING "0.30.3"

#endif
