name: PR Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go_version: 
          - "1.20"
          - "1.21"
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: install go-cov
        run: go install gitlab.com/matthewhughes/go-cov/cmd/go-cov
      - name: run tests
        run: |
          go test -coverprofile cov.out ./...
          go-cov cov.out > go-cov.out
      - name: check coverage
        shell: bash
        run: >
          awk '
          BEGIN {fail = 0}
          NR > 1 && $NF == 0 { fail = 1; printf("bad line: %s\n", $0) }
          END { if (fail) { exit(1) } }' go-cov.out
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
  check-generated-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup go
        uses: actions/setup-go@v4
      - name: generate code
        run: go generate ./...
      - name: check for changes in generated code
        run: |
          git add pkg
          if ! git diff --quiet -- pkg
          then
            echo 'changes detected from `go generate`' >&2
            exit 1
          fi

