name: PR Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go_version: ["1.19", "1.20"]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: install go-cov
        run: go install gitlab.com/matthewhughes/go-cov/cmd/go-cov
      - name: run tests
        run: |
          go test -coverprofile cov.out ./...
          go-cov cov.out > go-cov.out
      - name: check coverage
        shell: bash
        run: >
          awk '
          BEGIN {fail = 0}
          NR > 1 && $NF == 0 { fail = 1; printf("bad line: %s\n", $0) }
          END { if (fail) { exit(1) } }' go-cov.out
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      env:
        # run this separately since it handles it's own caching
        SKIP: golangci-lint
