name: tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go_version: ["1.19", "1.20"]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: run tests
        run: go test -coverprofile cov.out ./...
      - name: check coverage
        shell: bash
        run: >
          awk '
          BEGIN {fail = 0}
          NR > 1 && $NF == 0 { fail = 1; printf("bad line: %s\n", $0) }
          END { if (fail) { exit(1) } }'
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
